### ISSUE TITLE
Ao invés de utilizarmos uma base pronta poderíamos gerar uma base de verbos, locuções adverbiais, prepositivas e conjuntivas + palavras femininas

### ISSUE THREAD

**Issue by Mateus7Ribeiro** [gabrnunes/tem-crase#19]
• Poderíamos criar um algorítimo que identifique casos pela união entre verbos, locuções adverbiais, prepositivas e conjuntivas com (artigo feminino+preposição) unindo palavras femininas. (Seriam 3 bases de palavras)
• Criar uma base de exceções (+ 1 base de exceções)
• Além de permitir a comunidade votando a relevância dos resultados ou apontando erros.
• Podendo até treinar o modelo pra ele ser o mais perto possível de 100% de acertos.

**Comment by gabrnunes** [comment]
Massa @EnigmA737, essa era a minha ideia inicial, fazer algo mais voltado pra IA. Porém eu tenho muito pouco conhecimento sobre a área e não consegui sair do lugar... dai resolvi fazer do jeito que eu sabia pra tirar a ideia do papel hahaha.

Minha única preocupação é realmente criar essa base, pois TEM PALAVRA PRA CARAMBA hehe

**Comment by gabrnunes** [comment]
Acabei de ver que o criador do Term.ooo tem um dicionário aberto no Github, mas o que a gente conseguiria usar são apenas os verbos: https://github.com/fserb/pt-br

**Comment by EnigmA737** [comment]
@gabrnunes bora tentar amadurecer a ideia, tava estudando processamento de linguagem natural (PLN) ontem. Não procurei muito a fundo mas vi que tem pouca coisa nesse sentido para o português. Daria para puxarmos uma base de palavras de um dicionário e classificá-las. No PLN uma das formas de simplificar e tratar é reduzir a palavra para a própria raiz, sem nenhum sufixo ou variação de plural (pedreiro → pedr) não sei se ajudaria ou atrapalharia no caso das crases kkkk mas fica a ideia. 
Daria pra quebrar um dicionário ou fazer uma escavação nesses dicionários/base de palavras também.

**Comment by gabrnunes** [comment]
Massa, entendi! Acho que vale o estudo sim.
