### ISSUE TITLE
Adicionar forma de copiar o link para compartilhamento

### ISSUE THREAD

**Issue by gabrnunes** [gabrnunes/tem-crase#5]
Adicionar um botão para copiar o link para compartilhar com amigos

**Comment by RaphaelVRossi** [comment]
@gabrnunes Por favor, poderia passar a issue pro meu nome?!

**Comment by gabrnunes** [comment]
Você quer que eu faça um layout antes de implementar @RaphaelVRossi ?

**Comment by gabrnunes** [comment]
Ah, massa! Pode ser essa biblioteca sim, faz ai e dai eu vejo se precisa mexer em algo no layout depois :)

**Comment by gabrnunes** [comment]
Resolvido aqui: https://github.com/gabrnunes/tem-crase/pull/26
