### ISSUE TITLE
Criar bot para twitter

### ISSUE THREAD

**Issue by gabrnunes** [gabrnunes/tem-crase#8]
Eu já registrei o usuário @temcrase no twitter, minha ideia é que, toda pessoa que mandar um "volta as aulas @temcrase", ele responda conforme a busca na API.

Também daria pra fazer ele responder dúvidas gerais no twitter sobre crase.

**Comment by jrsmarcilio** [comment]
Olá @gabrnunes, fiz uma solicitação de candidatura para a API do Twitter e está sendo analisada a solicitação.
Dentro de 48hs eles retornaram com a resposta. Caso a candidatura seja aceita, gostaria de trabalhar nessa atividade.

**Comment by gabrnunes** [comment]
Boa, @jrsmarcilio só dá-lhe.

Acho que o ideal seria criar um novo repositório dai pro bot né?

**Comment by jrsmarcilio** [comment]
Isso @gabrnunes. Um repositório apenas para o bot seria o mais adequado.

**Comment by gabrnunes** [comment]
Twitter agora vai cobrar para criar API, não vale a pena.

**Comment by gabrnunes** [comment]
Twitter agora vai cobrar para criar API, não vale a pena.
